"""empty message

Revision ID: 7ce9c51b1f50
Revises: d80e360ad196
Create Date: 2022-03-06 18:17:58.886190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ce9c51b1f50'
down_revision = 'd80e360ad196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(length=256), nullable=True))
    op.drop_column('posts', 'summery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summery', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
